#!/bin/bash

export PATH="$HOME/.local/opt/calibre:$HOME/.local/opt/Wolfram/Mathematica/12.3/Executables:$HOME/.local/opt/texlive/2021/bin/x86_64-linux:$PATH"
export MANPATH="$HOME/.local/opt/texlive/2021/texmf-dist/doc/man:$MANPATH"
export INFOPATH="$HOME/.local/opt/texlive/2021/texmf-dist/doc/info:$INFOPATH"

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export ZSH_PYENV_LAZY_VIRTUALENV=true
export NVM_LAZY_LOAD=true
export NVM_LAZY_LOAD_EXTRA_COMMANDS=('lvim' 'nvim' 'j' 'n')

export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/home/aaronsms/.local/share/lunarvim"}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/home/aaronsms/.config/lvim"}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/home/aaronsms/.cache/nvim"}"
